### PR TITLE
Add ability to sprint when climbing on vertical climbable nodes.

### PR DESCRIPTION
**Pull request by randomei**
Sprint on ladders and other climbable nodes with aux1+sneak or aux1+jump.

### CODE REVIEW

**Review by BuckarooBanzay — COMMENTED** [review]
lgtm, haven't used and tested that mod though

**Comment by wsor4035** [comment]
i probably should test this. the more get node or nil calls are slightly 🤨 for performance

**Comment by randomei** [comment]
> i probably should test this. the more get node or nil calls are slightly 🤨 for performance

How can it be optimized?

**Comment by randomei** [comment]
OK, I've added check for keys pressed. Now "get node or nil" calls will only be used, when needed. I hope, this will improve performance.

**Comment by wsor4035** [comment]
Sorry, I was busy approving jam packages and stuff yesterday, I'll try and give this a review this afternoon

**Review by wsor4035 — APPROVED** [review]
seems legit, tested and works

**Comment by BuckarooBanzay** [comment]
thanks for looking into it :+1:

**Pull request merged**
