### PR TITLE
Color and localization

### PR DESCRIPTION
**Pull request by adikalon**
- The stamina bar changes color during the recovery period
- Localization (translation into Russian)

### CODE REVIEW

**Comment by wsor4035** [comment]
i looked at this last night, translation is fine, didnt actually test it yet, so not sure what purpose the color hudbar thing serves yet

**Comment by adikalon** [comment]
> so not sure what purpose the color hudbar thing serves yet

The mod has a parameter:
sprint_lite_stamina_threshold (Amount of stamina below which you can't start running)

If the indicator is below this value it changes color. Clearly shows why you cannot run at the moment

**Comment by wsor4035** [comment]
tested, works. a thought, maybe should use texture modifiers to recolor the texture instead of sending the client yet another texture

feel free to counter/say no

**Comment by adikalon** [comment]
Removed unnecessary textures

**Review by wsor4035 — APPROVED** [review]
seems legit, thanks

**Pull request merged**
